# MCP Servers Default Configuration
# Default MCP server definitions and categories

servers:
  filesystem:
    type: "stdio"
    command: "npx"
    args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
    env: {}
    description: "File system operations (read, write, list directories)"
    enabled: true
    category: "file_operations"

  fetch:
    type: "stdio"
    command: "node"
    args: ["C:\\work\\github\\fetch-mcp\\dist\\index.js"]
    env: {}
    description: "HTTP requests and web content fetching"
    enabled: true
    category: "web_operations"

  sqlite:
    type: "stdio"
    command: "npx"
    args: ["-y", "mcp-sqlite", "./data/tinyagent.db"]
    env: {}
    description: "SQLite database operations"
    enabled: false  # 包在Windows上有安装问题，暂时禁用
    category: "database_operations"
    
  my-search:
    type: "sse"
    url: "http://192.168.1.3:8081/sse"
    env: {}
    description: "Search the web via google and get content from web"
    enabled: true  # 启用SSE服务器 - 测试显示服务器正常
    category: "web_operations"
    
  sequential-thinking: 
    type: "stdio"
    command: "npx"
    args: ["-y", "@modelcontextprotocol/server-sequential-thinking"]
    env: {}
    description: "Sequential thinking operations"
    enabled: true  # 启用Sequential Thinking服务器
    category: "utility_operations"  

  time:
    type: "stdio"
    command: "npx"
    args: ["-y", "@modelcontextprotocol/server-time"]
    env: {}
    description: "Time operations"
    enabled: false  # 启用Time服务器
    category: "utility_operations"

# Server categories for organization
categories:
  file_operations:
    description: "File system and document operations"
    priority: "high"
    
  web_operations:
    description: "Web requests and content fetching"
    priority: "medium"
    
  database_operations:
    description: "Database queries and operations"
    priority: "low"
    
  utility_operations:
    description: "General utility tools"
    priority: "low"

# MCP client settings
client:
  timeout: 30
  max_retries: 3
  tool_cache_duration: 300
  max_tools_per_server: 50

# Enhanced Caching Configuration (EPIC-002)
caching:
  enabled: true
  cache_duration: 300  # 5分钟缓存持续时间
  max_cache_size: 100  # 最大缓存工具数
  performance_tracking: true
  persistent_cache: true
  cache_compression: false
  cache_cleanup_interval: 900  # 15分钟清理间隔
  
# Connection Pool Configuration (EPIC-002)
connection_pool:
  enabled: true
  max_connections_per_server: 3
  connection_timeout: 30
  retry_attempts: 3
  retry_delay: 1.0
  idle_timeout: 300  # 5分钟空闲超时
  health_check_interval: 60  # 1分钟健康检查间隔
  max_error_count: 5
  
# Performance Optimization Settings (EPIC-002)
performance:
  auto_discovery: true
  context_integration: true
  performance_monitoring: true
  benchmark_mode: false  # 启用性能基准测试模式
  metrics_collection: true
  async_tool_calls: true
  parallel_discovery: true
  
# Tool Context Integration (EPIC-002)
tools:
  context_builder:
    enabled: true
    max_context_length: 4000
    capability_mapping: true
    performance_weighting: true
    dynamic_recommendations: true 