# Development Profile Configuration
# 开发环境配置 - 只引用资源，不重复定义

agent:
  name: "TinyAgent-Dev"
  instructions_file: "prompts/default_instructions.txt"
  max_iterations: 5
  use_streaming: true  # 是否使用流式API进行工具调用日志记录

llm:
  active_provider: "openrouter"  # 引用 defaults/llm_providers.yaml 中的定义

mcp:
  enabled: true
  auto_discover: true
  # 开发环境启用的服务器
  enabled_servers:
    - "filesystem"
    - "fetch"
    - "sequential-thinking"
    # - "time"
    # - "my-search"

logging:
  level: "INFO"
  format: "structured"
  file: "${LOG_FILE:./logs/development.log}"

environment:
  env_file: ".env"
  env_prefix: "TINYAGENT_" 