# Development Profile Configuration
# 开发环境配置 - 只引用资源，不重复定义

agent:
  name: "TinyAgent-Dev"
  instructions_file: "prompts/default_instructions.txt"
  max_iterations: 5
  use_streaming: true  # 是否使用流式API进行工具调用日志记录
  intelligent_mode: true  # Enable intelligent ReAct mode
  
  # Intelligence configuration
  max_reasoning_iterations: 10
  confidence_threshold: 0.8
  max_concurrent_actions: 5
  action_timeout: 60.0
  memory_max_context_turns: 20
  use_detailed_observation: true
  enable_learning: true

llm:
  active_provider: "openrouter"  # 引用 defaults/llm_providers.yaml 中的定义

mcp:
  enabled: true
  auto_discover: true
  # 开发环境启用的服务器 - 暂时只启用最稳定的服务器
  enabled_servers:
    - "filesystem"
    - "sequential-thinking"
    # 暂时禁用SSE服务器以避免异步生成器错误
    # - "my-search"  

logging:
  level: "INFO"
  console_level: "USER"      # Show only user-relevant info in console
  file_level: "DEBUG"        # Full technical details in file
  format: "user_friendly"    # Clean console format
  file: "logs/development.log"
  structured_file: "logs/metrics/dev-metrics.jsonl"  # JSON metrics
  max_file_size: "10MB"
  backup_count: 5
  enable_colors: true
  show_timestamps: false     # No timestamps in console for cleaner UX

environment:
  env_file: ".env"
  env_prefix: "TINYAGENT_" 