# Development Profile Configuration
# 开发环境配置 - 只引用资源，不重复定义

agent:
  name: "TinyAgent-Dev"
  instructions_file: "prompts/default_instructions.txt"
  max_iterations: 5
  use_streaming: true  # 是否使用流式API进行工具调用日志记录

llm:
  active_provider: "openrouter"  # 引用 defaults/llm_providers.yaml 中的定义

mcp:
  enabled: true
  auto_discover: true
  # 开发环境启用的服务器 - 只启用最稳定的服务器进行测试
  enabled_servers:
    - "filesystem"
    - "sequential-thinking"
    - "my-search"  # 启用SSE搜索服务器
    # - "fetch"  # 暂时禁用，连接有问题
    # - "time"
    # - "my-search"

logging:
  level: "INFO"
  console_level: "USER"      # Show only user-relevant info in console
  file_level: "DEBUG"        # Full technical details in file
  format: "user_friendly"    # Clean console format
  file: "logs/development.log"
  structured_file: "logs/metrics/dev-metrics.jsonl"  # JSON metrics
  max_file_size: "10MB"
  backup_count: 5
  enable_colors: true
  show_timestamps: false     # No timestamps in console for cleaner UX

environment:
  env_file: ".env"
  env_prefix: "TINYAGENT_" 