# Development Profile Configuration
# 优化的开发环境配置 - 只引用资源，不重复定义

agent:
  name: "TinyAgent-Dev"
  instructions_file: "prompts/default_instructions.txt"
  max_iterations: 5

llm:
  active_provider: "openrouter"  # 引用 defaults/llm_providers.yaml 中的定义

mcp:
  enabled: true   # 启用MCP功能用于工具集成
  auto_discover: true
  servers:
    filesystem:
      type: "stdio"
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
      env: {}
      description: "File system operations (read, write, list directories)"
      enabled: true
      category: "file_operations"

    fetch:
      type: "stdio"
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-fetch"]
      env: {}
      description: "HTTP requests and web content fetching"
      enabled: false  # 暂时禁用，连接有问题
      category: "web_operations"

    sqlite:
      type: "stdio"
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-sqlite", "./data/tinyagent.db"]
      env: {}
      description: "SQLite database operations"
      enabled: false  # 暂时禁用，连接有问题
      category: "database_operations"

logging:
  level: "DEBUG"
  format: "structured"
  file: "${LOG_FILE:./logs/development.log}"

environment:
  env_file: ".env"
  env_prefix: "TINYAGENT_" 