# TinyAgent 开发环境配置 (简化版)
# 可选配置文件 - 大部分用户不需要修改此文件
# 智能默认值已覆盖90%的使用场景

agent:
  name: "TinyAgent-Dev"
  max_iterations: 5
  use_streaming: true  
  intelligent_mode: true

llm:
  # 可选: 覆盖默认提供商 (默认已设为openrouter)
  active_provider: "openrouter"

mcp:
  enabled: true
  auto_discover: true
  # 启用的MCP服务器 (默认: filesystem, my-search)
  enabled_servers:
    - "filesystem"
    - "my-search"
    # 可选启用: "sequential-thinking" (较不稳定)

logging:
  level: "INFO"
  console_level: "USER"      # 控制台显示用户友好信息
  file_level: "DEBUG"        # 文件记录详细技术信息
  format: "user_friendly"    # 简洁控制台格式
  file: "logs/development.log"
  structured_file: "logs/metrics/dev-metrics.jsonl"
  enable_colors: true
  show_timestamps: false     # 控制台不显示时间戳，更简洁

# 注意: 所有其他配置使用内置智能默认值
# 如需更多自定义，请使用环境变量覆盖 