# Production Profile Configuration
# 生产环境配置 - 只引用资源，不重复定义

agent:
  name: "TinyAgent-Prod"
  instructions_file: "prompts/default_instructions.txt"
  max_iterations: 20

llm:
  active_provider: "openrouter"  # 引用 defaults/llm_providers.yaml 中的定义

mcp:
  enabled: true
  auto_discover: true
  # 生产环境启用所有服务器
  enabled_servers:
    - "filesystem"
    - "mysearch"
    - "sqlite"

logging:
  level: "INFO"
  format: "structured"
  file: "${LOG_FILE:/var/log/tinyagent/production.log}"

environment:
  env_file: ".env"
  env_prefix: "TINYAGENT_" 